# Generated by Django 3.2.6 on 2021-08-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gif', '0003_auto_20210817_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gif',
            name='categories',
        ),
    ]
