# Generated by Django 3.2.6 on 2021-08-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, to='films.Director'),
        ),
    ]
