# Generated by Django 3.2.6 on 2021-08-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.vehiclesize'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.vehicletype'),
        ),
    ]
