# Generated by Django 3.2.6 on 2021-08-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20210821_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(),
        ),
    ]
