# Generated by Django 3.2.6 on 2021-08-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('homeworld', models.CharField(max_length=50)),
                ('mass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('vehicle_class', models.CharField(max_length=50)),
                ('max_atmosphering_speed', models.CharField(max_length=50)),
            ],
        ),
    ]
