# Generated by Django 3.2.6 on 2021-08-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peoplecard',
            old_name='homeworld',
            new_name='home_world',
        ),
    ]
