# Generated by Django 3.2.6 on 2021-08-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_rename_homeworld_peoplecard_home_world'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_cards', models.ManyToManyField(to='trading.PeopleCard')),
                ('vehicle_cards', models.ManyToManyField(to='trading.VehicleCard')),
            ],
        ),
    ]
