# Generated by Django 3.2.6 on 2021-08-30 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210830_1152'),
        ('trading', '0003_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=1, max_length=50)),
                ('c_type', models.CharField(choices=[('P', 'People Card'), ('V', 'Vehicle Card')], max_length=2)),
                ('rarity', models.IntegerField(default=0)),
                ('owners', models.ManyToManyField(related_name='deck', to='accounts.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='peoplecard',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehiclecard',
            name='name',
        ),
        migrations.AlterField(
            model_name='peoplecard',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='peoplecard',
            name='mass',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehiclecard',
            name='max_atmosphering_speed',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
    ]
