# Generated by Django 3.2.6 on 2021-08-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_transaction_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card',
        ),
    ]
