# Generated by Django 3.2.6 on 2021-08-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0011_transaction_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trade_reciever',
        ),
        migrations.AddField(
            model_name='transaction',
            name='trade_reciever',
            field=models.ManyToManyField(related_name='trade_reciever', to='accounts.Profile'),
        ),
    ]
