# Generated by Django 3.2.6 on 2021-08-30 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0013_alter_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sender', to='accounts.profile'),
        ),
    ]
