# Generated by Django 3.2.6 on 2021-09-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='min_score_buy',
            field=models.IntegerField(default=200),
        ),
    ]
