# Generated by Django 3.2.6 on 2021-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210901_1549'),
        ('trading', '0014_card_min_score_buy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='owners',
            field=models.ManyToManyField(null=True, related_name='deck', to='accounts.Profile'),
        ),
    ]
