# Generated by Django 3.2.6 on 2021-08-30 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0014_alter_transaction_trade_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trade_reciever',
        ),
        migrations.AddField(
            model_name='transaction',
            name='trade_reciever',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trade_reciever', to='accounts.profile'),
        ),
    ]
