# Generated by Django 3.2.6 on 2021-09-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_alter_card_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
