# Generated by Django 3.2.6 on 2021-08-31 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0016_alter_transaction_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_reciever', to='accounts.profile'),
        ),
    ]
