# Generated by Django 3.2.6 on 2021-08-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_alter_transaction_trade_reciever'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='choice',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('R', 'REJECT'), ('P', 'PENDING')], default='P', max_length=10),
        ),
    ]
