# Generated by Django 3.2.6 on 2021-09-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210901_1549'),
        ('trading', '0018_buycardresponse_buycardtransaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BuyCardTransaction',
            new_name='SellCardTransaction',
        ),
    ]
