# Generated by Django 3.2.6 on 2021-08-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0019_transaction_trade_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offer_target', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trade_sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_offer', to='accounts.profile'),
        ),
    ]
