# Generated by Django 3.2.6 on 2021-08-31 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_topic_topic'),
        ('trading', '0020_auto_20210831_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_choice', models.BooleanField(null=True)),
                ('card', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades_respone', to='trading.card')),
                ('trade_reciever', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trade_reciever', to='accounts.profile')),
                ('trade_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_sender', to='accounts.profile')),
            ],
        ),
    ]
