# Generated by Django 3.2.6 on 2021-08-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_transactionresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionresponse',
            name='original_transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trading.transaction'),
        ),
    ]
