# Generated by Django 3.2.6 on 2021-09-02 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210901_1549'),
        ('trading', '0021_delete_buycardresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcardtransaction',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='accounts.profile'),
        ),
    ]
