# Generated by Django 3.2.6 on 2021-08-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_transactionresponse_original_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionresponse',
            name='original_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.transaction'),
        ),
    ]
