# Generated by Django 3.2.6 on 2021-09-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_sellcardtransaction_can_sell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellcardtransaction',
            name='can_sell',
        ),
    ]
