# Generated by Django 3.2.6 on 2021-09-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_remove_sellcardtransaction_can_sell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellcardtransaction',
            name='choice',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('R', 'REJECT'), ('P', 'PENDING'), ('C', 'COMPLETED')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='choice',
            field=models.CharField(choices=[('A', 'ACCEPT'), ('R', 'REJECT'), ('P', 'PENDING'), ('C', 'COMPLETED')], default='P', max_length=10),
        ),
    ]
