# Generated by Django 3.2.6 on 2021-09-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0026_auto_20210902_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
