# Generated by Django 3.2.6 on 2021-08-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
