# Generated by Django 3.2.6 on 2021-08-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topic',
            field=models.IntegerField(choices=[(1, 'Wookie'), (2, 'Hutt'), (3, 'Jedi'), (4, 'Stormtrooper')], default=4),
        ),
    ]
