# Generated by Django 3.2.6 on 2021-08-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topic',
            field=models.CharField(choices=[('1', 'Wookie'), ('2', 'Hutt'), ('3', 'Jedi'), ('4', 'StormTrooper(not recommended)')], max_length=4, null=True),
        ),
    ]
