# Generated by Django 3.2.6 on 2021-08-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210829_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.topic'),
        ),
    ]
