# Generated by Django 3.2.6 on 2021-08-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_film_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
