# Generated by Django 3.2.6 on 2021-08-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_film_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
