# Generated by Django 3.2.6 on 2021-08-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Good'), (4, 'Grate'), (5, 'Excellect')], null=True),
        ),
    ]
