# Generated by Django 3.2.6 on 2021-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('*', 'One'), ('**', 'Two'), ('***', 'Three'), ('****', 'Four'), ('*****', 'Five')], max_length=5, null=True),
        ),
    ]
