# Generated by Django 3.2.6 on 2021-08-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='gif',
            name='categories',
            field=models.CharField(choices=[('1', 'actions'), ('2', 'celebrities'), ('3', 'decades'), ('4', 'emotions'), ('5', 'sports'), ('6', 'food & drink'), ('7', 'anime'), ('8', 'memes'), ('9', 'movies'), ('10', 'tv')], default='asd', max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='gifs',
            field=models.ManyToManyField(blank=True, to='gif.Gif'),
        ),
    ]
