# Generated by Django 3.2.6 on 2021-08-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gif', '0006_auto_20210817_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='gif',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
