# Generated by Django 3.2.6 on 2021-08-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210818_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
