# Generated by Django 3.2.6 on 2021-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_date_completion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='date_completion',
        ),
    ]
