# Generated by Django 3.2.6 on 2021-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_date_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_completion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
