# Generated by Django 3.2.6 on 2021-09-01 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_card_min_score_buy'),
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.card'),
        ),
    ]
