# Generated by Django 3.2.6 on 2021-09-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_alter_card_owners'),
        ('admin_app', '0002_alter_store_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='card',
        ),
        migrations.AddField(
            model_name='store',
            name='card',
            field=models.ManyToManyField(related_name='store', to='trading.Card'),
        ),
    ]
