# Generated by Django 3.2.6 on 2021-09-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0003_auto_20210901_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='store1', max_length=20),
        ),
    ]
