# Generated by Django 3.2.6 on 2021-09-01 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_alter_card_owners'),
        ('admin_app', '0004_store_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='card',
        ),
        migrations.AddField(
            model_name='store',
            name='card',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='store', to='trading.card'),
        ),
    ]
