# Generated by Django 3.2.6 on 2021-09-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_alter_card_owners'),
        ('admin_app', '0005_auto_20210901_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='card',
        ),
        migrations.AddField(
            model_name='store',
            name='card',
            field=models.ManyToManyField(to='trading.Card'),
        ),
    ]
