# Generated by Django 3.2.6 on 2021-09-01 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0006_auto_20210901_2315'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
