# Generated by Django 3.2.6 on 2021-09-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0016_alter_card_owners'),
        ('admin_app', '0007_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cards', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.card')),
            ],
        ),
    ]
