# Generated by Django 3.2.6 on 2021-09-02 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0008_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='cards',
            new_name='store_card',
        ),
    ]
