# Generated by Django 3.2.6 on 2021-08-20 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalstation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='rentalstation',
            name='country',
        ),
    ]
