# Generated by Django 3.2.6 on 2021-08-20 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0007_auto_20210820_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleAtRentalStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rent.vehicle')),
            ],
        ),
    ]
