# Generated by Django 3.2.6 on 2021-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0008_vehicleatrentalstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleatrentalstation',
            name='departure_date',
            field=models.DateTimeField(null=True),
        ),
    ]
