# Generated by Django 3.2.6 on 2021-08-20 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0010_auto_20210820_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleatrentalstation',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='rent.rentalstation'),
        ),
    ]
